services:
  svelte-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 3000
      ORIGIN: ${ORIGIN}
      VITE_API_URL: ${VITE_API_URL}
      VITE_API_VERSION: ${VITE_API_VERSION}
      VITE_API_TIMEOUT: ${VITE_API_TIMEOUT}
    expose:
      - "3000"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - svelte-app
    restart: unless-stopped

